version: '3.8'

services:
  # 后端API服务
  backend:
    build: .
    container_name: mywebsite_backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - DATABASE_URL=sqlite+aiosqlite:///./data/mywebdb.db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./static:/app/static
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: mywebsite_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: mywebsite_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/static
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  redis_data: